//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingdomConfeitaria
{
    public partial class Login
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl alertContainer;
        protected global::System.Web.UI.HtmlControls.HtmlInputGenericControl txtEmail;
        protected global::System.Web.UI.HtmlControls.HtmlInputGenericControl txtTelefone;
        protected global::System.Web.UI.HtmlControls.HtmlInputCheckBox chkTemWhatsApp;
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtNome;
        protected global::System.Web.UI.WebControls.Button btnContinuar;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl alertContainer;
        protected global::System.Web.UI.WebControls.TextBox txtNomeCompletar;
        protected global::System.Web.UI.WebControls.TextBox txtTelefoneCompletar;
        protected global::System.Web.UI.WebControls.CheckBox chkTemWhatsAppCompletar;
        protected global::System.Web.UI.WebControls.Button btnCompletarCadastro;
    }
}

