//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta.
//
//     Alterações neste arquivo podem causar comportamento incorreto e serão perdidas se
//     o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingdomConfeitaria
{
    public partial class MeusDados
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl alertContainer;
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtNome;
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtEmail;
        protected global::System.Web.UI.HtmlControls.HtmlInputGenericControl txtTelefone;
        protected global::System.Web.UI.HtmlControls.HtmlInputPassword txtSenhaAtual;
        protected global::System.Web.UI.HtmlControls.HtmlInputPassword txtNovaSenha;
        protected global::System.Web.UI.HtmlControls.HtmlInputPassword txtConfirmarNovaSenha;
        protected global::System.Web.UI.WebControls.Button btnSalvar;
    }
}

