//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingdomConfeitaria
{
    public partial class VerReserva
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl clienteNome;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor linkMinhasReservas;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor linkLogin;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor linkLogout;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl conteudoContainer;
    }
}

