//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingdomConfeitaria.paginas
{
    public partial class Login
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl alertContainer;
        protected global::System.Web.UI.HtmlControls.HtmlInputGenericControl txtEmail;
        protected global::System.Web.UI.HtmlControls.HtmlInputPassword txtSenha;
        protected global::System.Web.UI.WebControls.Button btnEntrar;
    }
}

